# render.yaml
services:
  - type: web
    name: mktv5-render
    env: node
    plan: free
    region: oregon
    healthCheckPath: /api/health
    # ✅ INÍCIO DA CORREÇÃO: Adiciona as dependências de sistema para o QR Code funcionar
    build:
      apt:
        packages:
          - libnss3
          - libatk-bridge2.0-0
          - libcups2
          - libgtk-3-0
          - libxkbcommon0
          - libxss1
          - libasound2
          - libgbm1
          - chromium-browser
    # FIM DA CORREÇÃO
    buildCommand: "npm install && npm run build && npm run db:generate"
    startCommand: "npm run migrate:deploy && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FORCE_AUTH_BYPASS
        value: false
      - key: GEMINI_API_KEY
        value: AIzaSyBh6HdznlhY0Xvm-rKWMBuQh83xVlEdSd4
      - key: JWT_SECRET
        value: k3jHs9aF3dLmN5pQrT7vWxYz1bC4eI0oP2uV6iM/s=
      - key: JWT_EXPIRES_IN
        value: 8d
      - key: GRAPESJS_STUDIO_LICENSE_KEY
        value: bcea48b82acd486f90429a86ef8e5f42b6abdef35d0e486f8649b929acfde5df
      - key: DATABASE_URL
        fromDatabase:
          name: mktv5-render-db
          property: connectionString
      - key: PUPPETEER_EXECUTABLE_PATH # ✅ Aponta para o Chromium instalado
        value: /usr/bin/chromium-browser

databases:
  - name: mktv5-render-db
    plan: free
    databaseName: mktv5render
    user: mktv5renderuser
    region: oregon
