# render.yaml
services:
  - type: web
    name: mktv5-render
    env: node
    plan: free
    region: oregon
    healthCheckPath: /api/health
    build:
      apt:
        packages:
          - libnss3
          - libatk-bridge2.0-0
          - libcups2
          - libgtk-3-0
          - libxkbcommon0
          - libxss1
          - libasound2
          - libgbm1
          - chromium-browser
    # ✅ CORREÇÃO FINAL: Removido 'npm run db:generate'.
    # O build agora apenas instala as dependências e constrói a aplicação.
    buildCommand: "npm install && npm run build"
    
    # Este comando está correto e deve ser mantido.
    startCommand: "npm run migrate:deploy && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase: postgresql://mktv5renderuser:3CWm0J0MNNQAXdh71LBTDehOQLERdxig@dpg-d0t7v1u3jp1c73eaajpg-a.oregon-postgres.render.com/mktv5render_wb67
          name: mktv5-render-db
          property: connectionString
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - GRAPESJS_STUDIO_LICENSE_KEY : a588bab57a26417d829a73e27616d0233b3b7ba518ea4156a72f28517c14f616
      - JWT_SECRET : k3jHs9aF3dLmN5pQrT7vWxYz1bC4eI0oP2uV6iM/s=
      - GEMINI_API_KEY : AIzaSyBT9JrtIatLC_9sWL1LAOmu8OqqRbERuRw
      - APP_BASE_URL : https://mktv2.onrender.com
      - APP_BASE_URL : https://mktv2.onrender.com

databases:
  - name: mktv5-render-db
    plan: free
    databaseName: mktv5render
    user: mktv5renderuser
    region: oregon
