import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { 
  Smartphone, 
  QrCode, 
  CheckCircle, 
  AlertCircle, 
  RefreshCw,
  Settings,
  Phone,
  MessageCircle,
  Shield,
  Zap,
  Copy,
  Download
} from 'lucide-react';

interface ConnectionStatus {
  isConnected: boolean;
  phoneNumber?: string;
  deviceName?: string;
  batteryLevel?: number;
  lastSeen?: string;
  qrCode?: string;
}

interface WhatsAppConnectionProps {
  onConnectionChange?: (status: ConnectionStatus) => void;
}

export default function WhatsAppConnection({ onConnectionChange }: WhatsAppConnectionProps) {
  const [connectionStatus, setConnectionStatus] = useState<ConnectionStatus>({
    isConnected: false,
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAUzklEQVR4Xu3dQY4cOQ4F0OmFd36l2fclzQKwjZI...' // Mock QR code - will be generated by real API
  });
  
  const [isLoading, setIsLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('connect');
  const [webhookUrl, setWebhookUrl] = useState('');
  const [apiToken, setApiToken] = useState('');

  // Simulate QR code refresh
  const refreshQRCode = async () => {
    setIsLoading(true);
    
    try {
      // In production, this would call your WhatsApp Business API
      // const response = await fetch('/api/whatsapp/generate-qr', { method: 'POST' });
      // const data = await response.json();
      
      // For now, simulate QR code generation
      setTimeout(() => {
        setConnectionStatus(prev => ({
          ...prev,
          qrCode: `data:image/png;base64,mock-qr-${Date.now()}`
        }));
        setIsLoading(false);
      }, 2000);
      
    } catch (error) {
      console.error('Erro ao gerar QR Code:', error);
      setIsLoading(false);
    }
  };

  // Simulate connection check
  const checkConnection = async () => {
    try {
      // In production, this would check the actual WhatsApp connection
      // const response = await fetch('/api/whatsapp/status');
      // const status = await response.json();
      
      // For demo purposes, randomly connect after a few seconds
      const isConnected = Math.random() > 0.3;
      
      const newStatus: ConnectionStatus = {
        isConnected,
        phoneNumber: isConnected ? '+55 11 99999-9999' : undefined,
        deviceName: isConnected ? 'iPhone 15 Pro' : undefined,
        batteryLevel: isConnected ? 85 : undefined,
        lastSeen: isConnected ? 'Agora' : undefined,
      };
      
      setConnectionStatus(newStatus);
      onConnectionChange?.(newStatus);
      
    } catch (error) {
      console.error('Erro ao verificar conexão:', error);
    }
  };

  // Auto-refresh QR code every 30 seconds
  useEffect(() => {
    if (!connectionStatus.isConnected) {
      const interval = setInterval(refreshQRCode, 30000);
      return () => clearInterval(interval);
    }
  }, [connectionStatus.isConnected]);

  // Check connection periodically
  useEffect(() => {
    const interval = setInterval(checkConnection, 5000);
    return () => clearInterval(interval);
  }, []);

  const generateQRCode = () => {
    // This creates a realistic QR code pattern for demo
    // In production, this would be the actual WhatsApp QR from the API
    const canvas = document.createElement('canvas');
    canvas.width = 256;
    canvas.height = 256;
    const ctx = canvas.getContext('2d');
    
    if (ctx) {
      // Create a simple QR-like pattern
      ctx.fillStyle = '#000';
      for (let i = 0; i < 256; i += 8) {
        for (let j = 0; j < 256; j += 8) {
          if (Math.random() > 0.5) {
            ctx.fillRect(i, j, 8, 8);
          }
        }
      }
      
      // Add positioning squares (typical QR code markers)
      ctx.fillStyle = '#000';
      // Top-left corner
      ctx.fillRect(0, 0, 56, 56);
      ctx.fillStyle = '#fff';
      ctx.fillRect(8, 8, 40, 40);
      ctx.fillStyle = '#000';
      ctx.fillRect(16, 16, 24, 24);
      
      // Top-right corner
      ctx.fillStyle = '#000';
      ctx.fillRect(200, 0, 56, 56);
      ctx.fillStyle = '#fff';
      ctx.fillRect(208, 8, 40, 40);
      ctx.fillStyle = '#000';
      ctx.fillRect(216, 16, 24, 24);
      
      // Bottom-left corner
      ctx.fillStyle = '#000';
      ctx.fillRect(0, 200, 56, 56);
      ctx.fillStyle = '#fff';
      ctx.fillRect(8, 208, 40, 40);
      ctx.fillStyle = '#000';
      ctx.fillRect(16, 216, 24, 24);
    }
    
    return canvas.toDataURL();
  };

  const copyWebhookUrl = () => {
    const url = `${window.location.origin}/api/webhooks/whatsapp`;
    navigator.clipboard.writeText(url);
  };

  const downloadQRCode = () => {
    const qrData = generateQRCode();
    const link = document.createElement('a');
    link.download = 'whatsapp-qr-code.png';
    link.href = qrData;
    link.click();
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">Conexão WhatsApp Business</h2>
          <p className="text-muted-foreground">
            Configure e gerencie sua conexão com WhatsApp Business API
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Badge 
            variant={connectionStatus.isConnected ? "default" : "destructive"}
            className="flex items-center space-x-1"
          >
            {connectionStatus.isConnected ? (
              <CheckCircle className="w-3 h-3" />
            ) : (
              <AlertCircle className="w-3 h-3" />
            )}
            <span>{connectionStatus.isConnected ? 'Conectado' : 'Desconectado'}</span>
          </Badge>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="connect">Conectar</TabsTrigger>
          <TabsTrigger value="status">Status</TabsTrigger>
          <TabsTrigger value="settings">Configurações</TabsTrigger>
        </TabsList>

        <TabsContent value="connect" className="space-y-4">
          {!connectionStatus.isConnected ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* QR Code Section */}
              <Card className="neu-card">
                <CardHeader>
                  <CardTitle className="flex items-center space-x-2">
                    <QrCode className="w-5 h-5" />
                    <span>Conectar via QR Code</span>
                  </CardTitle>
                  <CardDescription>
                    Escaneie o QR Code com seu WhatsApp Business
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex justify-center">
                    <div className="neu-card p-4 bg-white">
                      {isLoading ? (
                        <div className="w-64 h-64 flex items-center justify-center">
                          <RefreshCw className="w-8 h-8 animate-spin text-primary" />
                        </div>
                      ) : (
                        <img 
                          src={generateQRCode()} 
                          alt="WhatsApp QR Code" 
                          className="w-64 h-64"
                        />
                      )}
                    </div>
                  </div>
                  
                  <Alert>
                    <Smartphone className="h-4 w-4" />
                    <AlertDescription>
                      <strong>Como conectar:</strong>
                      <br />1. Abra o WhatsApp Business no seu celular
                      <br />2. Toque em Mais opções (⋮) → Dispositivos conectados
                      <br />3. Toque em "Conectar um dispositivo"
                      <br />4. Aponte seu celular para esta tela para escanear o código
                    </AlertDescription>
                  </Alert>

                  <div className="flex space-x-2">
                    <Button 
                      variant="outline" 
                      onClick={refreshQRCode}
                      disabled={isLoading}
                      className="flex-1 neu-button"
                    >
                      <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
                      Renovar QR Code
                    </Button>
                    <Button 
                      variant="outline" 
                      onClick={downloadQRCode}
                      className="neu-button"
                    >
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>

              {/* Instructions */}
              <Card className="neu-card">
                <CardHeader>
                  <CardTitle className="flex items-center space-x-2">
                    <Shield className="w-5 h-5" />
                    <span>Conexão Segura</span>
                  </CardTitle>
                  <CardDescription>
                    Sua conexão é protegida por criptografia end-to-end
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-start space-x-3">
                      <div className="w-6 h-6 bg-green-100 text-green-600 rounded-full flex items-center justify-center text-sm font-semibold">
                        1
                      </div>
                      <div>
                        <p className="font-medium">Escaneie o QR Code</p>
                        <p className="text-sm text-muted-foreground">
                          Use a câmera do WhatsApp Business
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-start space-x-3">
                      <div className="w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm font-semibold">
                        2
                      </div>
                      <div>
                        <p className="font-medium">Autorize a conexão</p>
                        <p className="text-sm text-muted-foreground">
                          Confirme no seu dispositivo móvel
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-start space-x-3">
                      <div className="w-6 h-6 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center text-sm font-semibold">
                        3
                      </div>
                      <div>
                        <p className="font-medium">Comece a usar</p>
                        <p className="text-sm text-muted-foreground">
                          Envie e receba mensagens pelo painel
                        </p>
                      </div>
                    </div>
                  </div>

                  <Alert>
                    <Zap className="h-4 w-4" />
                    <AlertDescription>
                      <strong>Dica:</strong> Mantenha seu celular conectado à internet para sincronização automática das mensagens.
                    </AlertDescription>
                  </Alert>
                </CardContent>
              </Card>
            </div>
          ) : (
            <Card className="neu-card">
              <CardContent className="p-6">
                <div className="text-center space-y-4">
                  <div className="w-16 h-16 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto">
                    <CheckCircle className="w-8 h-8" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-green-600">WhatsApp Conectado!</h3>
                    <p className="text-muted-foreground">
                      Sua conta está conectada e pronta para uso
                    </p>
                  </div>
                  <Button className="neu-button">
                    <MessageCircle className="w-4 h-4 mr-2" />
                    Ir para Conversas
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="status" className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="neu-card">
              <CardHeader>
                <CardTitle>Status da Conexão</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Status</span>
                  <Badge variant={connectionStatus.isConnected ? "default" : "destructive"}>
                    {connectionStatus.isConnected ? 'Conectado' : 'Desconectado'}
                  </Badge>
                </div>
                
                {connectionStatus.phoneNumber && (
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Número</span>
                    <span className="font-mono">{connectionStatus.phoneNumber}</span>
                  </div>
                )}
                
                {connectionStatus.deviceName && (
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Dispositivo</span>
                    <span>{connectionStatus.deviceName}</span>
                  </div>
                )}
                
                {connectionStatus.batteryLevel && (
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Bateria</span>
                    <span>{connectionStatus.batteryLevel}%</span>
                  </div>
                )}
                
                {connectionStatus.lastSeen && (
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Última vez online</span>
                    <span>{connectionStatus.lastSeen}</span>
                  </div>
                )}
              </CardContent>
            </Card>

            <Card className="neu-card">
              <CardHeader>
                <CardTitle>Estatísticas de Hoje</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Mensagens enviadas</span>
                  <span className="font-semibold">147</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Mensagens recebidas</span>
                  <span className="font-semibold">89</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Conversas ativas</span>
                  <span className="font-semibold">23</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Taxa de resposta</span>
                  <span className="font-semibold text-green-600">94%</span>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="settings" className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card className="neu-card">
              <CardHeader>
                <CardTitle>Configurações da API</CardTitle>
                <CardDescription>
                  Configure os parâmetros de conexão com WhatsApp Business API
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="api-token">Token da API</Label>
                  <Input
                    id="api-token"
                    type="password"
                    value={apiToken}
                    onChange={(e) => setApiToken(e.target.value)}
                    placeholder="Digite seu token da WhatsApp Business API"
                    className="neu-input"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="phone-id">Phone Number ID</Label>
                  <Input
                    id="phone-id"
                    placeholder="123456789012345"
                    className="neu-input"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="business-id">Business Account ID</Label>
                  <Input
                    id="business-id"
                    placeholder="Digite o ID da sua conta business"
                    className="neu-input"
                  />
                </div>
                
                <Button className="w-full neu-button">
                  <Settings className="w-4 h-4 mr-2" />
                  Salvar Configurações
                </Button>
              </CardContent>
            </Card>

            <Card className="neu-card">
              <CardHeader>
                <CardTitle>Webhook Configuration</CardTitle>
                <CardDescription>
                  Configure os webhooks para receber eventos em tempo real
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label>URL do Webhook</Label>
                  <div className="flex space-x-2">
                    <Input
                      value={`${window.location.origin}/api/webhooks/whatsapp`}
                      readOnly
                      className="neu-input"
                    />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={copyWebhookUrl}
                      className="neu-button"
                    >
                      <Copy className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="verify-token">Verify Token</Label>
                  <Input
                    id="verify-token"
                    value="USB_MKT_PRO_WEBHOOK_TOKEN"
                    readOnly
                    className="neu-input"
                  />
                </div>

                <Alert>
                  <Shield className="h-4 w-4" />
                  <AlertDescription>
                    Configure esta URL no painel do Facebook Developers para receber mensagens e eventos do WhatsApp.
                  </AlertDescription>
                </Alert>
                
                <Button className="w-full neu-button">
                  <Zap className="w-4 h-4 mr-2" />
                  Testar Webhook
                </Button>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}